### ISSUE TITLE
Unhappy on OSX 10.9.5

### ISSUE THREAD

**Issue by gavinandresen** [vinumeris/lighthouse#113]
Downloaded Lighthouse.dmg, installed, ran, crashed with:

```
Crash at Fri, 16 Jan 2015 21:20:03 GMT
Lighthouse/21
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2927)
	at lighthouse.utils.GuiUtils.informationalAlert(GuiUtils.java:75)
	at lighthouse.Main$3.onPeerConnected(Main.java:437)
	at org.bitcoinj.core.PeerGroup$10.run(PeerGroup.java:1270)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
	at com.sun.javafx.application.PlatformImpl$$Lambda$48/1550748714.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl$$Lambda$47/584634336.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)


04:20:01 13 Main.reached: [182ms / 0ms / 0ms] JFX initialised
04:20:01 13 UserPrefs.<init>: Could not load user prefs, using defaults.
04:20:02 13 PeerGroup.startAsync: Starting up with no attached block chain. Did you forget to pass one to the constructor?
04:20:02 21 PeerGroup$7.run: Starting ...
04:20:02 21 PeerGroup$5.go: Localhost peer detected, trying to use it instead of P2P discovery
04:20:02 13 Main.reached: [1085ms / 903ms / 903ms] Starting bitcoin init
04:20:02 24 WalletAppKit.startUp: Starting up with directory = /Users/gavin/Library/Application Support/Lighthouse/production
04:20:02 22 NioClientManager.handleKey: Successfully connected to /127.0.0.1:8333
04:20:02 22 Peer.connectionOpened: Announcing to /127.0.0.1:8333 as: /bitcoinj:0.13-SNAPSHOT/
04:20:02 22 Peer.processVersionMessage: Connected to 127.0.0.1: version=70002, subVer='/Satoshi:0.10.0/', services=0x1, time=2015-01-16 16:20:01, blocks=339250
04:20:02 22 PeerGroup.handleNewPeer: [127.0.0.1]:8333: New peer
04:20:02 22 PeerGroup.setDownloadPeer: Setting download peer: [127.0.0.1]:8333
04:20:03 24 MnemonicCode.toSeed: PBKDF2 took 257ms
04:20:03 24 KeyChainGroup.addAndActivateHDChain: Creating and activating a new HD chain: org.bitcoinj.wallet.DeterministicKeyChain@776fbc07
04:20:03 24 DeterministicKeyChain.maybeLookAhead: 1 keys needed for M/0H/0 = 1 issued + 0 lookahead size + 0 lookahead threshold - 0 num children
04:20:03 24 DeterministicKeyChain.maybeLookAhead: Took 1 msec
04:20:03 24 SPVBlockStore.<init>: Creating new SPV block chain file /Users/gavin/Library/Application Support/Lighthouse/production/Lighthouse.spvchain
04:20:03 24 CheckpointManager.readBinary: Read 165 checkpoints, hash is c1e72ea4ae3e909eb26ca508bd0df9ff7ab7265a7395aaa1c4251d553b11fbaf
04:20:03 24 AbstractBlockChain.<init>: chain head is at height 332640:
v2 block: 
   previous block: 00000000000000001133acacb92e43e24af63a487923361a4a98c87a5550dffe
   merkle root: 05296ceac7348c8aaea29c271216806eacabc3bae4e1cc2179d0c24b7bc48a0d
   time: [1417563705] 2014-12-02T23:41:45Z
   difficulty target (nBits): 404454260
   nonce: 965066629

04:20:03 24 AbstractBlockChain.addWallet: Wallet/chain height mismatch: 0 vs 332640
04:20:03 24 AbstractBlockChain.addWallet: Hashes: null vs 000000000000000005050188c4b38ab58644e1b69aad22dcc99e819d1deb0bb5
04:20:03 26 DiskManager.loadAll: Updating all data from disk
04:20:03 24 Main.reached: [1458ms / 0ms / 0ms] onSetupCompleted
04:20:03 26 DiskManager.loadAll: ... disk data loaded
04:20:03 25 DeterministicKeyChain.maybeLookAhead: 133 keys needed for M/0H/0 = 1 issued + 100 lookahead size + 33 lookahead threshold - 1 num children
04:20:03 26 DirectoryWatcher.<init>: Starting directory watch service for [/Users/gavin/Library/Application Support/Lighthouse/production]
04:20:03 25 DeterministicKeyChain.maybeLookAhead: Took 82 msec
04:20:03 25 DeterministicKeyChain.maybeLookAhead: 133 keys needed for M/0H/1 = 0 issued + 100 lookahead size + 33 lookahead threshold - 0 num children
04:20:03 25 DeterministicKeyChain.maybeLookAhead: Took 58 msec
04:20:03 26 LighthouseBackend.lambda$new$6: Backend initialized ...
04:20:03 25 PeerGroup$7.run: Starting ...
04:20:03 25 PeerGroup$5.go: Localhost peer detected, trying to use it instead of P2P discovery
04:20:03 30 NioClientManager.handleKey: Successfully connected to /127.0.0.1:8333
04:20:03 30 Peer.connectionOpened: Announcing to /127.0.0.1:8333 as: /bitcoinj:0.13-SNAPSHOT/Lighthouse:21/
04:20:03 30 Peer.processVersionMessage: Connected to 127.0.0.1: version=70002, subVer='/Satoshi:0.10.0/', services=0x1, time=2015-01-16 16:20:02, blocks=339250
04:20:03 30 PeerGroup.handleNewPeer: [127.0.0.1]:8333: New peer
04:20:03 30 PeerGroup.setDownloadPeer: Setting download peer: [127.0.0.1]:8333
04:20:03 30 DownloadProgressTracker.startDownload: Downloading block chain of size 6610. This may take a while.
04:20:03 13 Main.waitForInit: Waiting for bitcoin load ...
04:20:03 13 Main.waitForInit: Waiting for backend init ...
04:20:03 13 LHUtils.stopwatched: Loading main.fxml: 566ms
04:20:03 13 Main.reached: [1666ms / 1484ms / 581ms] Showing main UI
04:20:03 30 TxConfidenceTable.seen: [127.0.0.1]:8333: Peer announced new transaction [1] c8d5ef326c74c48435186789cb8d34b3551244ec7331aadbd0acc89cdb175012
04:20:03 30 TxConfidenceTable.seen: [127.0.0.1]:8333: Peer announced new transaction [1] eb12b0f8d9702ecf849b4dd5078e655322a21b6c3aef64467bc7f7ee9ce4ecd2
04:20:03 30 DownloadProgressTracker.progress: Chain download 1% done with 6543 blocks to go, block date 2014-12-03T15:54:20Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 2% done with 6477 blocks to go, block date 2014-12-04T01:48:33Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 3% done with 6411 blocks to go, block date 2014-12-04T12:45:55Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 4% done with 6345 blocks to go, block date 2014-12-05T00:02:52Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 5% done with 6279 blocks to go, block date 2014-12-05T10:45:55Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 6% done with 6213 blocks to go, block date 2014-12-05T19:31:07Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 7% done with 6147 blocks to go, block date 2014-12-06T06:27:49Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 8% done with 6081 blocks to go, block date 2014-12-06T17:48:52Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 9% done with 6015 blocks to go, block date 2014-12-07T06:24:22Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 10% done with 5949 blocks to go, block date 2014-12-07T19:42:26Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 11% done with 5882 blocks to go, block date 2014-12-08T06:14:55Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 12% done with 5816 blocks to go, block date 2014-12-08T16:29:27Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 13% done with 5750 blocks to go, block date 2014-12-09T03:40:45Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 14% done with 5684 blocks to go, block date 2014-12-09T14:59:41Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 15% done with 5618 blocks to go, block date 2014-12-10T00:49:45Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 16% done with 5552 blocks to go, block date 2014-12-10T10:04:14Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 17% done with 5486 blocks to go, block date 2014-12-10T22:33:01Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 18% done with 5420 blocks to go, block date 2014-12-11T09:30:07Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 19% done with 5354 blocks to go, block date 2014-12-11T19:20:35Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 20% done with 5288 blocks to go, block date 2014-12-12T06:06:24Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 21% done with 5221 blocks to go, block date 2014-12-12T17:18:06Z
04:20:03 13 WalletFiles.saveNow: Saving wallet, last seen block is 334075/0000000000000000168cce97058e2ab102bfb202b378572bf3238a26e17782fb
04:20:03 32 Updater.downloadSignedIndex: Requesting https://www.vinumeris.com/lighthouse/updates/index
04:20:03 13 WalletFiles.saveNowInternal: Save completed in 14msec
04:20:03 30 DownloadProgressTracker.progress: Chain download 22% done with 5155 blocks to go, block date 2014-12-13T06:18:46Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 23% done with 5089 blocks to go, block date 2014-12-13T16:09:01Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 24% done with 5023 blocks to go, block date 2014-12-14T03:01:50Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 25% done with 4957 blocks to go, block date 2014-12-14T15:12:46Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 26% done with 4891 blocks to go, block date 2014-12-15T02:21:55Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 27% done with 4825 blocks to go, block date 2014-12-15T12:54:33Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 28% done with 4759 blocks to go, block date 2014-12-16T00:58:53Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 29% done with 4693 blocks to go, block date 2014-12-16T12:03:55Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 30% done with 4627 blocks to go, block date 2014-12-16T22:25:16Z
04:20:03 31 WalletFiles$1.call: Background saving wallet, last seen block is 334640/00000000000000000c789133d6a2ba9f11cb40fad59f3bec042189376fbfe933
04:20:03 31 WalletFiles.saveNowInternal: Save completed in 12msec
04:20:03 13 Main$3.onPeerConnected: Localhost peer does not have support for NODE_GETUTXOS, ignoring
04:20:03 30 DownloadProgressTracker.progress: Chain download 31% done with 4560 blocks to go, block date 2014-12-17T12:04:11Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 32% done with 4494 blocks to go, block date 2014-12-17T23:26:43Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 33% done with 4428 blocks to go, block date 2014-12-18T10:29:32Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 34% done with 4362 blocks to go, block date 2014-12-18T23:58:30Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 35% done with 4296 blocks to go, block date 2014-12-19T12:27:07Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 36% done with 4230 blocks to go, block date 2014-12-19T23:20:40Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 37% done with 4164 blocks to go, block date 2014-12-20T10:49:34Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 38% done with 4098 blocks to go, block date 2014-12-20T22:57:46Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 39% done with 4032 blocks to go, block date 2014-12-21T09:48:25Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 40% done with 3966 blocks to go, block date 2014-12-21T20:48:57Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 41% done with 3899 blocks to go, block date 2014-12-22T09:51:24Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 42% done with 3833 blocks to go, block date 2014-12-22T20:32:25Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 43% done with 3767 blocks to go, block date 2014-12-23T04:58:19Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 44% done with 3701 blocks to go, block date 2014-12-23T16:22:54Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 45% done with 3635 blocks to go, block date 2014-12-24T01:34:26Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 46% done with 3569 blocks to go, block date 2014-12-24T14:02:26Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 47% done with 3503 blocks to go, block date 2014-12-24T22:04:48Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 48% done with 3437 blocks to go, block date 2014-12-25T07:31:52Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 49% done with 3371 blocks to go, block date 2014-12-25T18:09:44Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 50% done with 3305 blocks to go, block date 2014-12-26T04:57:02Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 51% done with 3238 blocks to go, block date 2014-12-26T16:34:29Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 52% done with 3172 blocks to go, block date 2014-12-27T01:46:09Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 53% done with 3106 blocks to go, block date 2014-12-27T10:13:36Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 54% done with 3040 blocks to go, block date 2014-12-27T22:10:18Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 55% done with 2974 blocks to go, block date 2014-12-28T07:48:29Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 56% done with 2908 blocks to go, block date 2014-12-28T16:53:28Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 57% done with 2842 blocks to go, block date 2014-12-29T02:08:05Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 58% done with 2776 blocks to go, block date 2014-12-29T12:19:02Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 59% done with 2710 blocks to go, block date 2014-12-29T21:49:32Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 60% done with 2644 blocks to go, block date 2014-12-30T10:21:07Z
04:20:03 31 WalletFiles$1.call: Background saving wallet, last seen block is 336640/00000000000000000ea8e1488c87d5960bdd4a5b243a8a545abce50f5c4f9bba
04:20:03 31 WalletFiles.saveNowInternal: Save completed in 7msec
04:20:03 30 DownloadProgressTracker.progress: Chain download 61% done with 2577 blocks to go, block date 2014-12-30T18:53:30Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 62% done with 2511 blocks to go, block date 2014-12-31T03:13:59Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 63% done with 2445 blocks to go, block date 2014-12-31T15:21:26Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 64% done with 2379 blocks to go, block date 2015-01-01T00:38:57Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 65% done with 2313 blocks to go, block date 2015-01-01T11:10:04Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 66% done with 2247 blocks to go, block date 2015-01-01T20:16:49Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 67% done with 2181 blocks to go, block date 2015-01-02T05:57:39Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 68% done with 2115 blocks to go, block date 2015-01-02T16:10:42Z
04:20:03 30 DownloadProgressTracker.progress: Chain download 69% done with 2049 blocks to go, block date 2015-01-03T02:24:48Z
```

**Comment by mikehearn** [comment]
Are you running a local Bitcoin node? If so, could you shut it down and try again?

**Comment by mikehearn** [comment]
Yeah, this bug occurs when there's a local node that doesn't support getutxo. It crashes trying to display the error message. Looks like I changed the message without retesting, oops.

**Comment by mikehearn** [comment]
OK, I pushed an update that fixes this. If you shut down Core, start the app, let it update, then you should be able to start Core again and use the app. Thanks for the testing!
