### ISSUE TITLE
CNF Exception in Lighthouse Client during Wallet Setup

### ISSUE THREAD

**Issue by joeschmid** [vinumeris/lighthouse#114]
> (pull latest lighthouse from github)
> mvn package -DskipTests
> java -jar client/target/shaded.jar
> Click "Setup Wallet"
> Click "Set Password"
> Enter password twice & click "Set Password"

Crash at Sat, 17 Jan 2015 21:31:47 GMT

java.lang.ClassNotFoundException: com.lambdaworks.crypto.SCrypt
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.bitcoinj.crypto.KeyCrypterScrypt.deriveKey(KeyCrypterScrypt.java:157)
	at lighthouse.subwindows.WalletSetPasswordController$IdealPasswordParameters.<init>(WalletSetPasswordController.java:91)
	at lighthouse.subwindows.WalletSetPasswordController.setPasswordClicked(WalletSetPasswordController.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1757)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1645)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8216)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3724)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3452)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1728)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2461)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:348)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:273)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:382)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:553)
	at com.sun.glass.ui.View.notifyMouse(View.java:925)

04:31:33 12 Main.reached: [696ms / 0ms / 0ms] JFX initialised
04:31:33 12 UserPrefs.<init>: Could not load user prefs, using defaults.
04:31:34 12 PeerGroup.startAsync: Starting up with no attached block chain. Did you forget to pass one to the constructor?
04:31:34 20 PeerGroup$7.run: Starting ...
04:31:34 20 PeerGroup.maybeCheckForLocalhostPeer: Localhost peer not detected.
04:31:34 12 Main.reached: [1899ms / 1203ms / 1203ms] Starting bitcoin init
04:31:34 22 WalletAppKit.startUp: Starting up with directory = /Users/joe/Library/Application Support/Crowdfunding App/production
04:31:35 22 MnemonicCode.toSeed: PBKDF2 took 462ms
04:31:35 22 KeyChainGroup.addAndActivateHDChain: Creating and activating a new HD chain: org.bitcoinj.wallet.DeterministicKeyChain@1519a8de
04:31:35 22 WalletProtobufSerializer.loadExtensions: Loading wallet extension com.vinumeris.lighthouse
04:31:35 22 PledgingWallet$PledgeStorage.deserializeWalletExtension: Wallet has 0 pledges in it
04:31:35 22 AbstractBlockChain.<init>: chain head is at height 339373:
v2 block: 
   previous block: 0000000000000000008a4bb705cf2b1771fa6544b3b5b8b2ebe4daf00f65d1f5
   merkle root: 39f6ab5354ac5431523bbe03f71d20d71bb25c16bf5932a3c6a9aadfd059984a
   time: [1421519946] 2015-01-17T18:39:06Z
   difficulty target (nBits): 404291887
   nonce: 2743414698

**Comment by joeschmid** [comment]
I was able to fix this by adding Maven dependencies for Orchid and Scrypt in client/pom.xml. Pull request created: https://github.com/vinumeris/lighthouse/pull/115

**Comment by mikehearn** [comment]
Thanks, merged
