### ISSUE TITLE
RejectedTransactionException

### ISSUE THREAD

**Issue by mikehearn** [vinumeris/lighthouse#116]
Example crash stack below. The issue is that we treat any reject at all as a failure and trigger the crash handling flow. This isn't right - we should only treat a transaction as fully rejected if all (or just most?) of the peers reject it. Right now we are vulnerable to old 0.9.2 nodes rejecting because we attach the low fee to our transactions, although the fee drop was put in about a year ago.

This involves a tweak to bitcoinj.

```
org.bitcoinj.core.RejectedTransactionException: Reject: tx XXX for reason 'insufficient fee' (66)
	at org.bitcoinj.core.TransactionBroadcast$1.onPreMessageReceived(TransactionBroadcast.java:76)
	at org.bitcoinj.core.Peer.processMessage(Peer.java:324)
	at org.bitcoinj.core.PeerSocketHandler.receiveBytes(PeerSocketHandler.java:178)
	at org.bitcoinj.net.ConnectionHandler.handleKey(ConnectionHandler.java:217)
	at org.bitcoinj.net.NioClientManager.handleKey(NioClientManager.java:88)
	at org.bitcoinj.net.NioClientManager.run(NioClientManager.java:124)
	at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
	at com.google.common.util.concurrent.Callables$3.run(Callables.java:93)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by mikehearn** [comment]
This should be fixed now.
