### ISSUE TITLE
Crash on diskPledgesChanged

### ISSUE THREAD

**Issue by slush0** [vinumeris/lighthouse#120]
Application crashed immediately after putting file to observed folder:

java.lang.NullPointerException
	at lighthouse.LighthouseBackend.diskPledgesChanged(LighthouseBackend.java:353)
	at lighthouse.LighthouseBackend.lambda$onDiskProjectAdded$7(LighthouseBackend.java:328)
	at lighthouse.LighthouseBackend$$Lambda$423/79780866.onChanged(Unknown Source)
	at com.sun.javafx.collections.SetListenerHelper$SingleChange.fireValueChangedEvent(SetListenerHelper.java:163)
	at com.sun.javafx.collections.SetListenerHelper.fireValueChangedEvent(SetListenerHelper.java:72)
	at com.sun.javafx.collections.ObservableSetWrapper.callObservers(ObservableSetWrapper.java:128)
	at com.sun.javafx.collections.ObservableSetWrapper.remove(ObservableSetWrapper.java:287)
	at lighthouse.files.DiskManager.onDirectoryChanged(DiskManager.java:175)
	at lighthouse.files.DiskManager$$Lambda$222/1991521747.accept(Unknown Source)
	at lighthouse.files.DirectoryWatcher.lambda$null$56(DirectoryWatcher.java:51)
	at lighthouse.files.DirectoryWatcher$$Lambda$226/557539926.run(Unknown Source)
	at lighthouse.threading.AffinityExecutor$ServiceAffinityExecutor.lambda$execute$40(AffinityExecutor.java:125)
	at lighthouse.threading.AffinityExecutor$ServiceAffinityExecutor$$Lambda$202/739885780.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Crashed whilst showing the crash dialog, giving up
java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = JavaFX Application Thread
	at com.sun.glass.ui.Application.checkEventThread(Application.java:445)
	at com.sun.glass.ui.Application.isNestedLoopRunning(Application.java:546)
	at com.sun.javafx.tk.quantum.QuantumToolkit.isNestedLoopRunning(QuantumToolkit.java:1066)
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:521)
	at javafx.stage.Stage.showAndWait(Stage.java:462)
	at com.vinumeris.crashfx.CrashWindow.lambda$open$5(CrashWindow.java:63)
	at com.vinumeris.crashfx.CrashWindow$$Lambda$479/1745874867.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$164(PlatformImpl.java:292)
	at com.sun.javafx.application.PlatformImpl$$Lambda$59/672802887.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$165(PlatformImpl.java:291)
	at com.sun.javafx.application.PlatformImpl$$Lambda$58/902125667.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$45(GtkApplication.java:126)
	at com.sun.glass.ui.gtk.GtkApplication$$Lambda$49/1923806853.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by slush0** [comment]
After restart everything is fine and I see the pledge (yay!)

**Comment by mikehearn** [comment]
Recent regression as part of a different bugfix ... not sure why I never hit this path in my own testing, but different operating systems and file systems can send quite unexpected sequences of change events. Disk observation has turned out to be a huge pain the ass.

I will push an update to fix this crash either today or tomorrow, once a few more bug reports roll in and get fixed. Will close the issue once the update goes out. Thanks for testing slush!

**Comment by slush0** [comment]
You're welcome! No worry, such problems are absolutely normal for multiplatform client-side apps (that's why I like server side programming more). Btw I see lot of potential in Lighthouse.

**Comment by mikehearn** [comment]
Yeah, I guess the equivalent sort of bug for server side apps is "this doesn't work in Internet Explorer 8" :-)

**Comment by mikehearn** [comment]
Should be fixed
